### ISSUE TITLE
Questions on installation

### ISSUE THREAD

**Issue by moshthepitt** [onaio/ansible-sqitch#3]
Please see: https://sqitch.org/download/debian/

Questions:

1.  When installing from ubuntu package repositories, should we make it configurable to also install the other required things to make it work with, say postgresql, mysql, sqlite3 etc? e.g. `ibdbd-pg-perl postgresql-client` for postgres, `libdbd-sqlite3-perl sqlite3` for sqlite, etc?

**Comment by lincmba** [comment]
@moshthepitt it is good to have this too. Will work on it.
